# vim:ft=kitty

## name: Oscura Midnight
## license: MIT
## author: Fey
## upstream: https://github.com/narative/oscura


background #0B0B0F
foreground #E6E6E6
selection_background #5A5B63
selection_foreground #E6E6E6
url_color #479FFA
cursor #E6E6E6
cursor_text_color #0B0B0F

# Tabs
active_tab_background #0B0B0F
active_tab_foreground #E6E6E6
inactive_tab_background #0B0B0F
inactive_tab_foreground #9592A4
tab_bar_background #0B0B0F

# Windows
active_border_color #E6E6E6
inactive_border_color #202127

# normal
color0 #0B0B0F
color1 #D84F68
color2 #54C0A3
color3 #E6E7A3
color4 #479FFA
color5 #9592A4
color6 #54C0A3
color7 #E6E6E6

# bright
color8  #46474F
color9  #FF5C5C
color10 #54C0A3
color11 #F9B98C
color12 #479FFA
color13 #9592A4
color14 #54C0A3
color15 #FFFFFF
